name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Accor"
    labels:
      - "accor"
  - title: "Sonesta"
    labels:
      - "sonesta"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR $BODY"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
replacers:
  # Extract content from "#### Tickets" section until next ####
  - search: '/\#\#\#\# Tickets\n(.*)\n\n\#\#\#\#/s'
    replace: "$1"
  # Replace newlines with commas
  - search: '/(.*)\n/g'
    replace: "$1,"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
