name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Accor"
    labels:
      - "accor"
  - title: "Sonesta"
    labels:
      - "sonesta"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR {{{$BODY}}}"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
replacers:
  # Replace each pr body with just the tickets
  - search: '/{{{.*#### Tickets\n(.*)\n\n#### Description.*}}}/s'
    replace: "{{{$1}}}"
  # Convert newlines to commas for ticket lists only (not affecting other content)
  - search: '/\n(?=[^{]*}}})/gs'
    replace: "$1, "
  # Make markers into list instead
  - search: '/{{{$1}}}/gs'
    replace: "[$1]"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
