name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "<img src='https://raw.githubusercontent.com/vollmerr/poc-release-drafter/HEAD/.github/assets/accor-logo.svg' width='16' height='16' alt='Accor Logo'> Accor"
    label: "accor"
  - title: "<img src='https://raw.githubusercontent.com/vollmerr/poc-release-drafter/HEAD/.github/assets/sonesta-logo.svg' width='16' height='16' alt='Sonesta Logo'> Sonesta"
    label: "sonesta"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE (#$NUMBER) - {{{$BODY}}} - @$AUTHOR"
replacers:
  # Remove invalid pr bodys
  - search: "/ - {{{(?:(?!#### Tickets)(?!}}})[^])*?}}}/gs"
    replace: ""
  # Replace each pr body with just the tickets
  - search: '/{{{.*?#### Tickets\s*\n(.*?)\s*\n\s*#### Description.*?}}}/gs'
    replace: "{{{$1}}}"
  # Convert newlines into commas for tickets
  - search: '/(\s+)(?=[^{]*}}})/g'
    replace: ", "
  # Normalize ticket formats - convert bare URLs to [TICKET](URL) format
  - search: '/(?<!\]\()https:\/\/eleven\.atlassian\.net\/browse\/([A-Z]+-\d+)/g'
    replace: "[$1](https://eleven.atlassian.net/browse/$1)"
  # Normalize bare ticket IDs to [TICKET](URL) format
  - search: '/(?<!\[)(?<!browse\/)([A-Z]+-\d+)(?!\]\()(?!\))/g'
    replace: "[$1](https://eleven.atlassian.net/browse/$1)"
  # Make markers into list instead
  - search: "/{{{(.*?)}}}/gs"
    replace: "[$1]"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
