name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Accor"
    labels:
      - "accor"
  - title: "Sonesta"
    labels:
      - "sonesta"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR $BODY"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
replacers:
  # Extract content from "#### Tickets" section until next #### or empty line, convert to comma-separated list
  - search: '/#### Tickets\s*(?:<!---[^>]*-->\s*)?(.*?)(?=####|^\s*$)/gms'
    replace: '$1'
  # Replace newlines with commas and clean up whitespace in the extracted tickets
  - search: '/([A-Z]+-\d+|\[[A-Z]+-\d+\]\([^)]+\))\s*\n\s*([A-Z]+-\d+|\[[A-Z]+-\d+\]\([^)]+\))/g'
    replace: '$1, $2'
  # Clean up any remaining newlines in ticket lists
  - search: '/([A-Z]+-\d+|\[[A-Z]+-\d+\]\([^)]+\))\s*\n+\s*/g'
    replace: '$1 '
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
