name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Accor"
    labels:
      - "accor"
  - title: "Sonesta"
    labels:
      - "sonesta"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE (#$NUMBER) {{{$BODY}}} @$AUTHOR"
replacers:
  # Remove invalid pr bodys
  - search: "/{{{(?:(?!#### Tickets)(?!}}})[^])*?}}}/gs"
    replace: ""
  # Replace each pr body with just the tickets
  - search: '/{{{.*?#### Tickets\s*\n(.*?)\s*\n\s*#### Description.*?}}}/gs'
    replace: "{{{$1}}}"
  # Convert newlines into commas for tickets
  - search: '/(\s+)(?=[^{]*}}})/g'
    replace: ", "
  # Make markers into list instead
  - search: "/{{{(.*?)}}}/gs"
    replace: "[$1]"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
